config/routes.rb
Rails.application.routes.draw do

  resources :tipo_tropas
	#redireccion a root para usuario y administrador (distinto) tras el login
  get 'dashboard/menu_user' => "dashboard#menu_user", as: :user_root

  get 'dashboard/menu_admin' => "dashboard#menu_admin", as: :admin_root


  get 'dashboard/mostrar_tropas', to: 'dashboard#mostrar_tropas'

  get 'dashboard/adquirir_tropa/:id', to: 'dashboard#adquirir_tropa', as: 'nueva_tropa'

  get 'dashboard/mostrar_recursos', to: 'dashboard#mostrar_recursos'

  get 'dashboard/add_recurso/:id', to: 'dashboard#add_recurso', as: 'add_recurso'

  get 'dashboard/atacar/', to: 'dashboard#atacar'

  get 'dashboard/retirarse/', to: 'dashboard#retirarse', as: 'retirarse'

  get 'dashboard/atacar_enemigo/:id', to: 'dashboard#atacar_enemigo', as: 'atacar_enemigo'



  devise_for :admins
  devise_for :users
  resources :recursos

  resources :tropas

  # setear el root como el login de usuario
  devise_scope :user do
  root to: "devise/sessions#new"
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def menu_user
 	if current_admin
  		redirect_to "dashboard#menu_admin"
  	elsif not signed_in?
  		redirect_to "/"
  	end

  @tropas = current_user.tropas_por_usuarios

  end

  def menu_admin
  	if current_user
  		redirect_to "dashboard#menu_user"
  	elsif not signed_in?
  		redirect_to "/"
  	end

  end

  def mostrar_tropas
    @tropas = Tropa.all
  end

  def adquirir_tropa

     @tropa = Tropa.find(params[:id])

     @new_tropa = @tropa.tropas_por_usuarios.build(:user => current_user)
     @new_tropa.fecha = Time.now
     @new_tropa.curr_atk = @tropa.atk
     @new_tropa.curr_def = @tropa.def
    respond_to do |format|
      if @new_tropa.save
        @recurso = current_user.recursos_por_usuarios.where(recurso_id: @new_tropa.tropa.recurso_id).first
        @cantidad = @recurso.cantidad-@new_tropa.tropa.cantidad_rec
        if @recurso.update_attributes(:cantidad => @cantidad)

          format.html { redirect_to dashboard_mostrar_tropas_path, notice: 'Tropa adquirida exitosamente' }

        else
          format.html { redirect_to dashboard_mostrar_tropas_path, notice: 'Error al adquirir tropa' }

        end
      else
        format.html { redirect_to dashboard_mostrar_tropas_path, notice: 'Error al adquirir tropa' }

      end
    end
  end

  def mostrar_recursos
    @recursos = Recurso.all
  end

  def retirarse
    @recursos = RecursosPorUsuario.where(user_id: current_user.id)
    @recursos.each do |recurso|
      @cantidad = recurso.cantidad - 1
      recurso.update_attributes(:cantidad => @cantidad, :ultima_fecha => Time.now)
    end
    respond_to do |format|
      format.html {redirect_to dashboard_mostrar_recursos_path, notice: 'Te has retirado y has perdido 1 de cada recurso'}
    end
  end

  def atacar
    @enemigo = User.where.not(email:current_user.email).order("RANDOM()").first
    @tropas_enemigo = @enemigo.tropas_por_usuarios
    @suma_ataque = @tropas_enemigo.sum(:curr_atk)
    @suma_defensa = @tropas_enemigo.sum(:curr_def)
  end

  def atacar_enemigo
  end

  def add_recurso
    @recurso = Recurso.find(params[:id])

    if RecursosPorUsuario.where(user_id: current_user.id, recurso_id: params[:id]).exists?
      @new_recurso = RecursosPorUsuario.where(user_id: current_user.id, recurso_id: params[:id]).first
      @cantidad = @new_recurso.cantidad + 100
      respond_to do |format|
        if @new_recurso.update_attributes(:cantidad => @cantidad, :ultima_fecha => Time.now)
          format.html { redirect_to dashboard_mostrar_recursos_path, notice: '+ 100 ' }
        else
          format.html { redirect_to dashboard_mostrar_tropas_path, notice: 'Error al adquirir recurso' }
        end
      end

    else
      @new_recurso = @recurso.recursos_por_usuarios.build(:user => current_user)
      @new_recurso.cantidad = 100
      @new_recurso.ultima_fecha = Time.now
      respond_to do |format|
        if @new_recurso.save
          format.html { redirect_to dashboard_mostrar_recursos_path, notice: '+ 100 ' }
        else
          format.html { redirect_to dashboard_mostrar_tropas_path, notice: 'Error al adquirir recurso' }
        end
      end
    end
  end



end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/atacar.html.erb
<table>

  <tbody>
    <td> Total Ataque: <%= @suma_ataque %> </td> <br>
    <td> Total Defensa: <%= @suma_defensa %> </td>

  </tbody>
</table>

<br>

<td><%= link_to 'Retirarse', retirarse_path %></td>
<td><%= link_to 'Atacar al enemigo', user_root_path %></td>

app/views/dashboard/menu_admin.html.erb
<h1>Menu Admin</h1>

<h2> por implementar </h2>

app/views/dashboard/menu_user.html.erb
<h1> Sus tropas </h1>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th> Fecha Adquisición</th>
      <th>Ataque</th>
      <th>Defensa</th>
      <th> Tipo Tropa </th>

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @tropas.each do |t| %>
      <tr>
        <td><%= t.tropa.nombre %></td>
        <td> <%= t.fecha %></td>
        <td><%= t.curr_atk %></td>
        <td><%= t.curr_def %></td>
        <td> <%= t.tropa.tipo_tropa.nombre%> </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/mostrar_recursos.html.erb
<p id="notice"><%= notice %></p>

<h1> Mis Recursos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th> Cantidad </th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @recursos.each do |recurso| %>
      <tr>
        <td><%= recurso.nombre %></td>
      <%
        @rec = recurso.recursos_por_usuarios.where(user_id: current_user.id).first
        if @rec
      %>
      <td><%= @rec.cantidad %></td>
      <%
          if Time.now - @rec.ultima_fecha >= 60
      %>
        <td><%= link_to 'Adquirir', add_recurso_path(recurso) %></td>
      <%
          end
       else %>
      <td> 0 </td>
      <td><%= link_to 'Adquirir', add_recurso_path(recurso) %></td>
      <%end %>

      </tr>
    <%
      end %>
  </tbody>
</table>

<br>

app/views/dashboard/mostrar_tropas.html.erb
<p id="notice"><%= notice %></p>

<h1>Tropas</h1>


<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ataque</th>
      <th>Defensa</th>
      <th> Tipo Tropa </th>
      <th> Recurso Necesario </th>
      <th> Cantidad de Recurso </th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @tropas.each do |tropa| %>
      <tr>
        <td><%= tropa.nombre %></td>
        <td><%= tropa.atk %></td>
        <td><%= tropa.def %></td>
        <td> <%= tropa.tipo_tropa.nombre%> </td>
        <td><%= tropa.recurso.nombre %></td>
        <td><%= tropa.cantidad_rec %></td>
        <% @rec = current_user.recursos_por_usuarios.where(recurso_id: tropa.recurso_id)
          if @rec.exists?
            @rec = @rec.first
            if @rec.cantidad >= tropa.cantidad_rec
        %>
              <td><%= link_to 'Adquirir', nueva_tropa_path(tropa) %></td>

      </tr>
    <%      end
          end
      end %>
  </tbody>
</table>

<br>