config/routes.rb
Rails.application.routes.draw do

  resources :tipo_tropas
	#redireccion a root para usuario y administrador (distinto) tras el login
  get 'dashboard/menu_user' => "dashboard#menu_user", as: :user_root

  get 'dashboard/menu_admin' => "dashboard#menu_admin", as: :admin_root


  get 'dashboard/mostrar_tropas', to: 'dashboard#mostrar_tropas'

  get 'dashboard/adquirir_tropa/:id', to: 'dashboard#adquirir_tropa', as: 'nueva_tropa'

  get 'dashboard/mostrar_recursos', to: 'dashboard#mostrar_recursos'

  get 'dashboard/add_recurso/:id', to: 'dashboard#add_recurso', as: 'add_recurso'

  get 'dashboard/atacar/', to: 'dashboard#atacar'

  get 'dashboard/retirarse/', to: 'dashboard#retirarse', as: 'retirarse'

  get 'dashboard/atacar_enemigo/:id', to: 'dashboard#atacar_enemigo', as: 'atacar_enemigo'



  devise_for :admins
  devise_for :users
  resources :recursos

  resources :tropas

  # setear el root como el login de usuario
  devise_scope :user do
  root to: "devise/sessions#new"
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recurso.rb
class Recurso < ApplicationRecord
	has_many :tropas

	has_many :recursos_por_usuarios
  has_many :users, :through => :recursos_por_usuarios
end

app/controllers/recursos_controller.rb
class RecursosController < ApplicationController
  before_action :set_recurso, only: [:show, :edit, :update, :destroy]

  def index
  	@recursos = Recurso.all
  end
  

  def show
  end

  
  def new
    @recurso = Recurso.new
  end

  
  def edit
  end

 
  def create
    @recurso = Recurso.new(recurso_params)

    respond_to do |format|
      if @recurso.save
        format.html { redirect_to @recurso, notice: 'Recurso creado exitosamente' }
    
      else
        format.html { render :new }
        
      end
    end
  end

  def update
    respond_to do |format|
      if @recurso.update(recurso_params)
        format.html { redirect_to @recurso, notice: 'Recurso Editado' }

      else
        format.html { render :edit }
       
      end
    end
  end


  def destroy
    @recurso.destroy
    respond_to do |format|
      format.html { redirect_to recursos_url, notice: 'Recursos Eliminados' }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurso
      @recurso = Recurso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recurso_params
      params.require(:recurso).permit(:nombre)
    end
end

app/helpers/recursos_helper.rb
module RecursosHelper
end

app/views/recursos/edit.html.erb
<h1>Editing Recurso</h1>

<%= form_for @recurso, url: recurso_path(@recurso) do |f| %>
  <% if @recurso.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recurso.errors.count, "error") %> prohibited
      this recurso from being saved:</h2>
    <ul>
    <% @recurso.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, id: :recurso_nombre %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @recurso %> |
<%= link_to 'Back', recursos_path %>

app/views/recursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recursos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @recursos.each do |recurso| %>
      <tr>
        <td><%= recurso.nombre %></td>
        <td><%= link_to 'Show', recurso %></td>
        <td><%= link_to 'Edit', edit_recurso_path(recurso) %></td>
        <td><%= link_to 'Destroy', recurso, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar Recurso', new_recurso_path %>

app/views/recursos/new.html.erb
<h1>New Recurso</h1>

<%= form_for :recurso, url: recursos_path do |f| %>
  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, id: :recurso_nombre %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', recursos_path %>

app/views/recursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @recurso.nombre %>
</p>


<%= link_to 'Edit', edit_recurso_path(@recurso) %> |
<%= link_to 'Back', recursos_path %>